### ISSUE TITLE
Feature Request - Fullscreen

### ISSUE THREAD

**Issue by Will-wastelander** [Sindarius/DWC_GCodeViewer_Plugin#1]
Being able to have a way to open a new tab with just the gcode viewer would be nice.

**Comment by Sindarius** [comment]
I am going to look into adding a full screen button. The original version of the viewer that I wrote used to pop out as an individual tab but most of the feedback I got was that they wanted it in the DWC itself. I think by adding a full screen button you can opt to open two tabs and devote one to a full windowed viewer.

**Comment by Will-wastelander** [comment]
Don't get me wrong, it's nice in DWC itself, but I'm only able to see about half of the view, then I have to scroll. If it was scalable to the size available, that could work also. But I think a full screen would be faster, especially if you have already done the code for it, which it sounds like you have.

**Comment by Sindarius** [comment]
Implemented in https://github.com/Sindarius/DWC_GCodeViewer_Plugin/commit/635ea987f830a291a7813de6fb9e5f00b190b7db
