### ISSUE TITLE
Firts scene render works well, subsequent renders fail

### ISSUE THREAD

**Issue by dabit20** [Sindarius/DWC_GCodeViewer_Plugin#2]
As discussed on the Duet forum: https://forum.duet3d.com/post/195548

Current config:
https://www.icecoldcomputing.com/directlink/DaBit3D_config_26nov2020.zip

Small(ish) G-code exhibiting the issue
[stackable_OD5.5_ID3.2_H3_bush_2_16x_0mm35_PETG.zip](https://github.com/Sindarius/DWC_GCodeViewer_Plugin/files/5608880/stackable_OD5.5_ID3.2_H3_bush_2_16x_0mm35_PETG.zip)

Large G-code file exhibiting the issue:
[mould_container_bot_2x_PETG.zip](https://github.com/Sindarius/DWC_GCodeViewer_Plugin/files/5608875/mould_container_bot_2x_PETG.zip)

System:
- DWC GCodeViewer_Plugin version 0.9.4, DWC 3.2.0-beta4, RRF 3.2-beta4 on a Duet2Wifi
- Windows 10 machine, AMD Ryzen 3700+RTX2070 videocard, latest Game Ready driver. 
- Browsers tried: Chrome version 86.0.4240.128,  Edge version 87.0.664.41 on Windows 10, Chrome browser on Android 7.

**Comment by Sindarius** [comment]
Fixed in https://github.com/Sindarius/DWC_GCodeViewer_Plugin/commit/0bafa9f7de9f5bf050b6dfd8c3652b16345eb938
