### ISSUE TITLE
beta4 plugin dont show after upload

### ISSUE THREAD

**Issue by sankafola** [Sindarius/DWC_GCodeViewer_Plugin#3]
i uploaded the new gcode plugin to system folder and it dont show as plugin under the " machine specific " plugin

**Comment by Sindarius** [comment]
Can you verify the versions of DWC you are running and the version of the plugin file you downloaded?  

You can check the plugin version by popping open the zip file and checking the json file

**Comment by sankafola** [comment]
hi,
    here is the info i found 

Duet Web Control 3.2.0-beta4
 <https://github.com/Duet3D/DuetWebControl>

and the plugin is this one https://github.com/Sindarius/DWC_GCodeViewer_Plugin/releases/download/0.11.1/GCodeViewer.zip <https://github.com/Sindarius/DWC_GCodeViewer_Plugin/releases/download/0.11.1/GCodeViewer.zip> 

my card is SKR Pro 
‘

**Comment by Sindarius** [comment]
When you go to the system and upload the zip file do you get a prompt asking if you want to install a plugin? Make sure you do not unzip the file when uploading it to the system.

**Comment by sankafola** [comment]
no i was not going giving me anything now it did and it works now,  thanks a lot for the tip
