### ISSUE TITLE
Can't install in DWC 3.22

### ISSUE THREAD

**Issue by StephenRC** [Sindarius/DWC_GCodeViewer_Plugin#5]
Can't install in DWC 3.2.2, it requires DWC 3.2.0.
Had to downgrade DWX to 3.2beta1 to get it to install.

**Comment by Sindarius** [comment]
You do not need to install this plugin since it is included in the Duet Web Control as of 3.2.  Go to Settings > General > Plugins and you'll be able to enable it.

**Comment by ShuffleBit** [comment]
> You do not need to install this plugin since it is included in the Duet Web Control as of 3.2. Go to Settings > General > Plugins and you'll be able to enable it.

It's not there on my 3.2.2 board, but perhaps it won't handle a board in CNC Mode. Subtractive vs additive, or something. There are no plugins at all under Settings->General->Plugins on my board.

**Comment by Sindarius** [comment]
There should be a few plugins default installed with the DWC. Can you verify the version of the DWC on the General tab. The GCode Viewer does work with CNC. it will show the bit's travel path from the gcode. It also supports G2/G3 which is much more common in the CNC world.


![Screen Shot 2021-02-25 at 10 43 12 AM](https://user-images.githubusercontent.com/12520045/109186187-49900480-7756-11eb-908e-0268296a1ec1.png)

**Comment by ShuffleBit** [comment]
It's 3.2.2, and the plugins showed up as soon as I cleared the browser cache and refreshed.
