### ISSUE TITLE
Port for mainsail possible?

### ISSUE THREAD

**Issue by afbenevides** [Sindarius/DWC_GCodeViewer_Plugin#6]
Hi @Sindarius, I was wondering if a port of this module to mainsail would be feasible? Do you have some thoughts?

Thanks.

**Comment by Sindarius** [comment]
I am not familiar with mainsail but I don’t see any reason why it couldn’t be done.

**Comment by Sindarius** [comment]
Just FYI this is an older version of the code since it has been moved in to the DWC baseline. Are you looking at attempting to make this port?

**Comment by markwalet** [comment]
I was just source-diving the Mainsail repository, looks like this package already is being used there.

Source: https://github.com/mainsail-crew/mainsail/blob/develop/src/components/gcodeviewer/Viewer.vue#L254

**Comment by Sindarius** [comment]
I moved a main part of the viewer to an NPM package some time ago and worked with the Mainsail team to integrate it. I'll be closing this ticket. 

Thanks
